### ISSUE TITLE
forçar quebra de linha no texto do ggplot

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/mob_acess_br2020#4]
Parece que o `aop_style()` nao permite forçar quebra de linha no texto do ggplot. @joaoparga , tem como concertar isso?

Exemplo reproduzivel abaixo:

### sem quebra
```
source("./R/setup.R")
source("./R/style.R")
source("./R/colours.R")

# Passageiros transportados
df_pass <- readxl::read_excel('./data/ntu.xlsx', sheet = 'passageiros')

ggplot(data=df_pass) +
  geom_point(aes(x=ano, y=volume, color=mes)) + 
  geom_line(aes(x=ano, y=volume, color=mes)) +
  labs(x= 'Ano', y='Passageiros equivalentes\n por veículo por dia', color='Mês') +
  scale_y_continuous(limits = c(100, 650), breaks = seq(100,700, 100) ) +
  scale_x_continuous(breaks = seq(min(df_pass$ano), max(df_pass$ano), by=2) ) +
  theme_minimal() +
  aop_style() 
```
![quebranao](https://user-images.githubusercontent.com/7448421/95025341-55701280-065f-11eb-975c-99a0f75fb976.png)

Agora sem usar o `aop_style()`  a gente consegue a quebra de linha:

```
ggplot(data=df_pass) +
  geom_point(aes(x=ano, y=volume, color=mes)) + 
  geom_line(aes(x=ano, y=volume, color=mes)) +
  labs(x= 'Ano', y='Passageiros equivalentes\n por veículo por dia', color='Mês') +
  scale_y_continuous(limits = c(100, 650), breaks = seq(100,700, 100) ) +
  scale_x_continuous(breaks = seq(min(df_pass$ano), max(df_pass$ano), by=2) ) +
  theme_minimal()

```

![quebnra](https://user-images.githubusercontent.com/7448421/95025355-72a4e100-065f-11eb-8d9b-cfc2434dadad.png)

**Comment by joaoparga** [comment]
Oi Rafael.

Com exceção do elemento `text` dentro da função `theme()` (que compõe a base do `aop_style()`), eu coloquei os componentes de texto (ex.: `plot.title`, `axis.text`, `axis.title`, etc.) como `ggtext::element_markdown()`. Desta forma, eles podem ser formatados como Markdown (seguindo o pacote ggtext: https://github.com/wilkelab/ggtext). Assim, para incluir uma quebra de texto, pode adicionar o código `<br>`.
No exemplo, ficaria: 

`labs(x= 'Ano', y='Passageiros equivalentes<br>por veículo por dia', color='Mês')`

Outro exemplo abaixo:

`ggplot() +
  geom_point(data = mpg, aes(cty, hwy)) +
  aop_style() +
  labs(
    x = 'Este é um teste para o nome do eixo x',
    y = 'Este é um teste para o nome do eixo y<br>com quebra de linha'
  )`

<img width="624" alt="Screen Shot 2020-10-04 at 16 54 52" src="https://user-images.githubusercontent.com/60621364/95025735-59e9fa80-0662-11eb-8ca1-7ded7b1114b5.png">


Não sei se colocar os elementos como `ggtext::element_markdown()` pode dar algum problema futuro, mas a princípio acho que esta solução parece OK. 
O que acha?

**Comment by rafapereirabr** [comment]
ah, saquei. Daí ele usa sintaxe de html. Sem problema. Usei o `<br>` e resolveu aqui 👍 
![plot_ntu](https://user-images.githubusercontent.com/7448421/95274623-b3962480-081c-11eb-965b-5699fa7042a4.png)
